=== sompower2003/BW_1/clg2.config/bw/clg2.configuration.shared/Schemas/ServiceConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
xmlns="http://globalgateway.mycorelogic.com/ServiceConfiguration" targetNamespace="http://globalgateway.mycorelogic.com/ServiceConfiguration"
 elementFormDefault="qualified" attributeFormDefault="unqualified" >
	<xsd:element name="serviceConfiguration">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="service" type="ServiceType" minOccurs="1" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="ServiceType">
		<xsd:sequence>
			<xsd:element name="conversation" type="ConversationType" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="request" type="ProcessingType" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="reply" type="ProcessingType" minOccurs="1" maxOccurs="1"/>
			<!-- The following two elements are only required for asynchronous conversation -->
			<xsd:element name="response" type="ProcessingType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="return" type="ProcessingType" minOccurs="0" maxOccurs="1"/>
		</xsd:sequence>
		<xsd:attribute name="name" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:pattern value="VALUATION|TITLE|GSEGRADE|FLOOD|LSFM|LSAM|TAX-SSOT"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	<xsd:complexType name="ProcessingType">
		<xsd:sequence>
			<xsd:element name="action" type="ActionType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="FlowType">
		<xsd:sequence>
			<xsd:element name="validationSchema" type="xsd:string"
				minOccurs="0" />
			<xsd:element name="extractStyleSheet" type="xsd:string" minOccurs="0"></xsd:element>
			<xsd:element name="styleSheet" type="xsd:string"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="ConversationType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="ASYNC|SYNC|ONEWAY"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="ActionType">
		<xsd:sequence>
			<xsd:element name="input" type="FlowType" minOccurs="1" maxOccurs="1"/>
			<!-- The output element is used for supporting canonical model based transformation -->
			<xsd:element name="output" type="FlowType" minOccurs="0" maxOccurs="1"/>		
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="transform" type="YNType" use="required"/>
		<xsd:attribute name="validate" type="YNType" use="required"/>
	</xsd:complexType>
	<xsd:simpleType name="YNType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="y|n"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== sompower2003/BW_1/clg2.config/bw/clg2.configuration.shared/Test/ServiceConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:serviceConfiguration xmlns:p="http://globalgateway.mycorelogic.com/ServiceConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://globalgateway.mycorelogic.com/ServiceConfiguration ../Schemas/ServiceConfiguration.xsd ">
  <p:service name="WF">
    <p:conversation>Async</p:conversation>
    <p:request>
      <p:action name="Submit" transform="y" validate="y">
        <p:input/>
      </p:action>
    </p:request>
    <p:reply>
      <p:action name="Recevied" transform="y" validate="y">
        <p:input/>
      </p:action>
    </p:reply>
  </p:service>
</p:serviceConfiguration>
